export const predefinedRooms = [
    "Living Room",
    "Bedroom",
    "Kitchen",
    "Bathroom",
    "Dining Room",
    "Office",
    "Hallway",
    "Garage",
    "Guest Room",
    "Nursery",
    "Basement",
    "Laundry Room",
    "Closet",
    "Entryway",
    "Stairway",
    "Porch",
    "Patio",
    "Garden",
    "Balcony",
    "Workshop",
    "Home Theater",
    "Gym",
];
